// One-off generator for src/data/cities.ts, run manually (see PROJECT_BRIEF.md).
// Source: `all-the-cities` (MIT-licensed npm package), itself derived from
// GeoNames.org (CC BY 4.0) -- the standard free global gazetteer, covering
// down to village/neighborhood-level named places (verified: includes both
// La Jolla, CA and Vadakku Viravanallur, Tamil Nadu).
const fs = require("fs");
const path = require("path");
const cities = require("all-the-cities");

const POPULATION_THRESHOLD = 15000;

// GeoNames' own admin1 (state/province) code -> name mapping, same source
// system as the city data above, so "CC.adminCode" always lines up. Fetched
// from https://download.geonames.org/export/dump/admin1CodesASCII.txt and
// checked in as-is (CC BY 4.0, ~3865 rows, rarely changes). Format per line:
// "CC.ADMIN1<TAB>Name<TAB>ASCII name<TAB>geonameid".
const ADMIN1_NAMES = {};
for (const line of fs.readFileSync(path.join(__dirname, "admin1CodesASCII.txt"), "utf8").split("\n")) {
  const [code, name] = line.split("\t");
  if (code) ADMIN1_NAMES[code] = name;
}

// A handful of India codes used in the (older, snapshotted) city dataset
// that the current admin1CodesASCII.txt no longer lists separately -- e.g.
// Dadra and Nagar Haveli (06) and Daman and Diu (32) were administratively
// merged into a single territory in 2020 and now only appear merged (52) in
// the current reference file. Verified by cross-checking every other India
// code against this same reference file first (all matched exactly) before
// falling back to this hand list for just the handful that didn't.
const INDIA_STATE_FALLBACK = {
  "06": "Dadra and Nagar Haveli",
  "32": "Daman and Diu",
};

const countryDisplay = new Intl.DisplayNames(["en"], { type: "region" });

function countryNameFor(city) {
  if (city.country === "IN") return "India";
  try {
    return countryDisplay.of(city.country) ?? city.country;
  } catch {
    return city.country;
  }
}

function stateFor(city) {
  const key = `${city.country}.${city.adminCode}`;
  return ADMIN1_NAMES[key] ?? INDIA_STATE_FALLBACK[city.adminCode] ?? countryNameFor(city);
}

const filtered = cities
  .filter((c) => c.population >= POPULATION_THRESHOLD)
  .map((c) => ({
    id: String(c.cityId),
    name: c.name,
    state: stateFor(c),
    country: countryNameFor(c),
    latitude: Math.round(c.loc.coordinates[1] * 10000) / 10000,
    longitude: Math.round(c.loc.coordinates[0] * 10000) / 10000,
  }))
  // India first (this app's primary audience), then the rest alphabetically
  // by country -- the Country/State/City cascading selects (PlaceSelector)
  // rely on this order for the country list.
  .sort((a, b) => {
    if (a.country !== b.country) {
      if (a.country === "India") return -1;
      if (b.country === "India") return 1;
      return a.country.localeCompare(b.country);
    }
    return a.state.localeCompare(b.state) || a.name.localeCompare(b.name);
  });

const header = `// Generated by web/scripts/generate-cities.cjs -- do not hand-edit.
// Source: `+"`all-the-cities`"+` (GeoNames-derived, population >= ${POPULATION_THRESHOLD}).
// Regenerate with: node scripts/generate-cities.cjs
export interface City {
  id: string;
  name: string;
  state: string;
  country: string;
  latitude: number;
  longitude: number;
}

export const CITIES: City[] = [
`;

const body = filtered
  .map(
    (c) =>
      `  { id: ${JSON.stringify(c.id)}, name: ${JSON.stringify(c.name)}, state: ${JSON.stringify(c.state)}, country: ${JSON.stringify(c.country)}, latitude: ${c.latitude}, longitude: ${c.longitude} },`,
  )
  .join("\n");

const footer = `\n];\n`;

fs.writeFileSync(path.join(__dirname, "../src/data/cities.ts"), header + body + footer);
console.log(`Wrote ${filtered.length} cities to src/data/cities.ts`);
